> ### Select Topic Area
> 
> Question
> 
> ### Body
> 
> A person has somehow taken over the private GitHub repository and has now publically exposed and reposted the repository with highly sensitive data and API how can github community be of help to take him down is report that person?

